micronaut:
  application:
    name: customerApp
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:mysql://localhost:3306/todaytix_henry?autoReconnect=true
    driverClassName: com.mysql.cj.jdbc.Driver
    pooled: true
    username: 'todaytix'
    password: 'todaytix'
    schema-generate: NONE
    dialect: MYSQL
jpa:
  default:
    entity-scan:
      packages: 'com.henry.domains'